source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'beatblackjack' do
  use_frameworks!

  # Pods for beatblackjack
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
end
